name: mt
channels:
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - python=3.7.10
  - numpy=1.20.2
  - scikit-learn=0.24.1
  - scipy=1.6.2
  - networkx=2.3
  - karateclub=1.0.23
  - gensim=3.8.3
  - docker-py=5.0.0
  - dash=1.20.0
