name: mt
channels:
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - python=3.7.10
  - numpy=1.20.2
  - scikit-learn=0.24.1
  - scipy=1.6.2
  - networkx=2.5.1
  - karateclub=1.0.23
  - gensim=3.8.3
  - pydot=1.2.4
  - docker-py=5.0.0
  - click=7.1.2
  - holoviews=1.14.3
  - bokeh=2.3.1
