name: ag
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.10
  - numpy=1.20.2
  - scikit-learn=0.24.2
  - scipy=1.6.3
  - networkx=2.5.1
  - karateclub=1.0.23
  - gensim=3.8.3
  - dash=1.20.0
  - cudatoolkit=10.2.89
  - pytorch=1.8.1
  - pip=21.1.1
